version: '2.0'

services:
  webgoat:
    image: webgoat/webgoat-8.0
    user: webgoat
    environment:
      - WEBWOLF_HOST=webwolf
      - spring.datasource.url=jdbc:postgresql://webgoat_db:5432/webgoat
      - spring.datasource.username=webgoat
      - spring.datasource.password=webgoat
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect
    ports:
      - "8080:8080"
  webwolf:
    image: webgoat/webwolf
    environment:
      - spring.datasource.url=jdbc:postgresql://webgoat_db:5432/webgoat
      - spring.datasource.username=webgoat
      - spring.datasource.password=webgoat
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect
    ports:
      - "8081:8081"
  db:
    container_name: webgoat_db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=webgoat
      - POSTGRES_USER=webgoat
      - POSTGRES_DB=webgoat
    ports:
      - "5432:5432"

